- name: Ensure db mount  
  file:
    path: "{{ mount_target }}"
    state: directory

- package: name=nfs-common state=installed
  tags: mount

- service: name=rpcbind enabled=true state=started
  tags: mount

- mount:
    src: "{{ mount_src }}"
    name: "{{ mount_target }}"
    fstype: nfs
    opts: rw,rsize=8192,wsize=8192,timeo=14,intr,vers=3
    state: mounted
  notify:
      - restart influxdb
  tags: mount

- name: install influxdb
  apt_key:
    id: 2582E0C5 
    url: "https://repos.influxdata.com/influxdb.key"
    state: present

- apt_repository:
    repo: deb https://repos.influxdata.com/debian jessie stable
    state: present
    filename: 'influxdb'

- apt: name=influxdb state=latest 

- ini_file:
    dest: /etc/influxdb/influxdb.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ influxdb_conf_items }}"
  notify: restart influxdb

- name: ensure influxdb is running
  systemd:
    name: influxdb
    daemon_reload: yes
    state: started
    enabled: yes

