- name: Ensure db mount  
  file:
    path: "{{ mount_target }}"
    state: directory

- package: name=nfs-common state=installed
  tags: mount

- service: name=rpcbind enabled=true state=started
  tags: mount

- mount:
    src: "{{ mount_src }}"
    name: "{{ mount_target }}"
    fstype: nfs
    opts: rw,rsize=8192,wsize=8192,timeo=14,intr,vers=3
    state: mounted
  notify:
      - restart influxdb
  tags: mount

- name: install influxdb
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/{{ influxdb_pkg }}"
    dest: "/var/tmp/{{ influxdb_pkg }}"
    checksum: "{{ influxdb_checksum }}"

- command: tar -C "{{ item.dest }}" --strip "{{ item.strip }}" -xf "{{ influxdb_pkg }}" "{{ item.files }}"
  args:
      chdir: /var/tmp
  with_items:
      - { dest: /etc,       strip: 3, files: "./{{ influxdb_version }}/etc/logrotate.d" }
      - { dest: /usr/local, strip: 3, files: "./{{ influxdb_version }}/usr/bin" }
      - { dest: /usr/local, strip: 3, files: "./{{ influxdb_version }}/usr/share" }
      - { dest: /var,       strip: 3, files: "./{{ influxdb_version }}/var/lib" }
      - { dest: /var,       strip: 3, files: "./{{ influxdb_version }}/var/log" }

- command: tar -C "{{ item.dest }}" --strip "{{ item.strip }}" -xf "{{ influxdb_pkg }}" "{{ item.files }}"
  args:
      chdir: /var/tmp
      creates: /etc/influxdb/influxdb.conf
  with_items:
      - { dest: /etc,  strip: 3, files: "./{{ influxdb_version }}/etc/influxdb" }

- ini_file:
    dest: /etc/influxdb/influxdb.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ influxdb_conf_items }}"
  notify: restart influxdb

- copy:
    src: influxdb.service
    dest: /etc/systemd/system/

- group:
    name: influxdb
    system: yes

- user:
    name: influxdb
    group: influxdb
    home: /var/lib/influxdb
    system: yes

- file:
    dest: "{{ item }}"
    owner: influxdb
    group: influxdb
    state: directory
  with_items:
      - /var/lib/influxdb
        #- "{{ influxdb_dir }}"

- name: ensure influxdb is running
  systemd:
    name: influxdb
    daemon_reload: yes
    state: started
    enabled: yes

